version: '2'
services:
  password:
    environment:
      MYSQL_ROOT_PASSWORD: password
      # MYSQL_USER: root
      MYSQL_PASSWORD: password
      JOYNTO_AWS_KEY_ID:
      JOYNTO_AWS_SECRET:
      TZ: "Asia/Tokyo"
