 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/warrants", type: :request do
  # Warrant. As you add validations to Warrant, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Warrant.create! valid_attributes
      get warrants_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      warrant = Warrant.create! valid_attributes
      get warrant_url(warrant)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_warrant_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      warrant = Warrant.create! valid_attributes
      get edit_warrant_url(warrant)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Warrant" do
        expect {
          post warrants_url, params: { warrant: valid_attributes }
        }.to change(Warrant, :count).by(1)
      end

      it "redirects to the created warrant" do
        post warrants_url, params: { warrant: valid_attributes }
        expect(response).to redirect_to(warrant_url(Warrant.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Warrant" do
        expect {
          post warrants_url, params: { warrant: invalid_attributes }
        }.to change(Warrant, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post warrants_url, params: { warrant: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested warrant" do
        warrant = Warrant.create! valid_attributes
        patch warrant_url(warrant), params: { warrant: new_attributes }
        warrant.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the warrant" do
        warrant = Warrant.create! valid_attributes
        patch warrant_url(warrant), params: { warrant: new_attributes }
        warrant.reload
        expect(response).to redirect_to(warrant_url(warrant))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        warrant = Warrant.create! valid_attributes
        patch warrant_url(warrant), params: { warrant: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested warrant" do
      warrant = Warrant.create! valid_attributes
      expect {
        delete warrant_url(warrant)
      }.to change(Warrant, :count).by(-1)
    end

    it "redirects to the warrants list" do
      warrant = Warrant.create! valid_attributes
      delete warrant_url(warrant)
      expect(response).to redirect_to(warrants_url)
    end
  end
end
